project: brainhackwarsaw/CIFAR10

name: CIFAR10
description: ""

environment: pytorch-1.0.0-gpu-py3
worker: s-k80
input:
- cifar_pytorch

parameters:
  epochs: 50
  learning_rate: 0.001
  batch_size: 32
  model: convnet1
  channel_sequence: "[16, 16, 32, 32]"
  fc_type: nonlinear_dropout
  block_type: 3x3->bn->1x1
  # fc_type: [linear, nonlinear, nonlinear_dropout]
  # block_type: [3x3, 3x3->1x1, 3x3->bn->1x1] # 3x3, 3x3->1x1, 3x3->bn->1x1

metric:
  channel: "Log-loss validation"
  goal: minimize
