project: brainhackwarsaw/CIFAR10

command:
- "sew.py"

name: CIFAR10
description: ""

input:
- cifar_pytorch
- /CIF-89/output/model.pth:model1.pth
- /CIF-89/output/model.pth:model2.pth

environment: pytorch-1.0.0-gpu-py3
worker: s-k80
tags: [sew]

parameters:
  epochs: 20
  learning_rate: 0.0001
  batch_size: 32
  model1_cut_at: 3
  model2_cut_at: 3
